--Adicionar pedido

SELECT * FROM CLIENTE c ;
SELECT * FROM PEDIDO p ;
SELECT * FROM ITEM_PEDIDO ip ;
SELECT * FROM PRODUTO p ;
SELECT * FROM STATUS_PEDIDO sp ;
SELECT * FROM VENDEDOR v ;
SELECT * FROM USUARIO u ;
SELECT * FROM LOJA_FISICA lf ;

--Insere nova ordem de pedido
INSERT INTO CLIENTE (COD_CLIENTE,COD_USUARIO)
VALUES(8,9);

INSERT INTO PEDIDO (COD_PEDIDO,DATA_PEDIDO,TEMPO_ESPERA,VALOR_TOTAL_PEDIDO,COD_CLIENTE,COD_VENDEDOR,COD_STATUS_PEDIDO,COD_LOJA)
VALUES(5,'2023-18-09 08:40','00:30',125.00,1,3,4,2);

INSERT INTO ITEM_PEDIDO (COD_ITEM_PEDIDO,QUANTIDADE,COD_PEDIDO,COD_PRODUTO)
VALUES(4,3,5,2);

INSERT INTO VENDEDOR (COD_VENDEDOR,COD_USUARIO,COD_LOJA)
VALUES(3,8,2);

--	Inner join para ver pedidos feitos
SELECT p.COD_PEDIDO AS Pedido , u.NOME AS Cliente,p2.NOME AS Produto,ip.QUANTIDADE AS Qtd,p.DATA_PEDIDO ,p.TEMPO_ESPERA AS Espera,p.VALOR_TOTAL_PEDIDO AS 'Valor Total' ,sp.DESCRICAO_STATUS AS Entrega,v.COD_LOJA AS Loja FROM PEDIDO p 
INNER JOIN VENDEDOR v 
ON p.COD_VENDEDOR = v.COD_VENDEDOR 
INNER JOIN CLIENTE c 
ON p.COD_CLIENTE = c.cod_cliente
INNER JOIN USUARIO u 
ON c.COD_USUARIO = u.COD_USUARIO 
INNER JOIN STATUS_PEDIDO sp 
ON sp.COD_STATUS_PEDIDO = p.COD_STATUS_PEDIDO 
INNER JOIN ITEM_PEDIDO ip 
ON p.COD_PEDIDO = ip.COD_PEDIDO 
INNER JOIN PRODUTO p2 
ON ip.COD_PRODUTO = p2.COD_PRODUTO 
Order by p.COD_PEDIDO ASC;
